### ISSUE TITLE
Refactor the code in order to implement a design pattern.

### ISSUE THREAD

**Issue by bkenza** [mohanadarafe/GuideMe#121]
In order to add some useful design patterns, the code needs to be refactored a bit since we did not really follow any architecture. By refactoring, we aim to make the code more _readable and reusable_. The purpose of this refactoring is to try to prevent future implementation issues and also, to make it more easy for more people to work on the same project.

**Comment by AlainJobs** [comment]
![image](https://user-images.githubusercontent.com/33582344/76237003-ebe07080-6203-11ea-93a5-2bdf57744823.png)

**Comment by AlainJobs** [comment]
## Done so far

- **Search and BottomMenu/MoreDetails functional components were refactored:**

MoreDetails is now called BuildingMoreDetails since the component design (logic/template) is specific to a building. 

- **Modified and added constant data elements:**
What's the point to have a list that is called a function? It is confusing to have all of our files as functions just for the sake of having functions. A function should be called as such when it has well-defined functionality. I did not delete any previous data constant files such as _BuildingData, sgwRooms & BuildingCoordinates._ I refactored those by adding the following constant data files as const variables that can be exported instead of a funciton : _buildingInformation, services, departments, classRooms._
- **MapData is refactored  and _is a potential candidate for a quick design pattern implementation.*_*
- **Search functional component is refactored**
- **BottomMenu/GetMoreBuildingDetails (changed the name) functional components were refactored.**
**- Change currentLocation to currentBuilding because that's what the function does (unless I'm wrong).**

**Comment by AlainJobs** [comment]
This issue will be moved to the refactoring endeavour and since we implemented a design pattern, this issue is not relevant.
