### ISSUE TITLE
[UPDATED FOR SPRINT 4] Acceptance Test #6 | US5:  As a user, I would like to know which building I am currently in & my current location.

### ISSUE THREAD

**Issue by mohanadarafe** [mohanadarafe/GuideMe#157]
### Story
As a user, I would like to know which building I am currently in & my current location.

### Steps to reproduce
1. Open the app
2. Press on the building icon in the bottom right for current building display (if available)
3. Press on the location icon in the bottom right for current location

**Note: due to COVID-19 outbreak, the altitude measurements are not precise*

### Preview
![ezgif-4-7224915cd863](https://user-images.githubusercontent.com/34899555/79669151-86c75580-8187-11ea-856a-8f98ad2f0baf.gif)

**Comment by jodavimehran** [comment]
I've tested this feature and it works. But I was thinking about it and I think that it would be better if you will merge it with the "Show my current location" story.
Because whenever you wanted to implement the "Show my current location" feature, you will need another button for it and it is not good to have two buttons one for the current building and another for the current location.
So when a user wanted to locate its current location, if it is located in a building you can select that building as a current building automatically and if the user is not located in any Concordia's building just do nothing. In this way, you can remove the pop-up Dialog and show the current building only as a selected building in the bottom of the page.

**Comment by mohanadarafe** [comment]
> I've tested this feature and it works. But I was thinking about it and I think that it would be better if you will merge it with the "Show my current location" story.
> Because whenever you wanted to implement the "Show my current location" feature, you will need another button for it and it is not good to have two buttons one for the current building and another for the current location.
> So when a user wanted to locate its current location, if it is located in a building you can select that building as a current building automatically and if the user is not located in any Concordia's building just do nothing. In this way, you can remove the pop-up Dialog and show the current building only as a selected building in the bottom of the page.

Updated for Sprint 4 ✅

**Comment by jodavimehran** [comment]
Accepted
