### ISSUE TITLE
Merge indoor and outdoor directions.

### ISSUE THREAD

**Issue by bkenza** [mohanadarafe/GuideMe#197]

**Comment by AlainJobs** [comment]
## Update
Only one scenario is missing to close this issue.
We have 4 scenarios. 
1. If origin and destination are classrooms from the same building (Merged)
2. If the origin is a classroom but not the destination (Merged).
3. If the destination is a classroom but not the origin (Merged).
4. If both origin and destination are classrooms but are from different buildings (Not merged) 

Some UI changes were made as well: 
- No need to refresh in the Preview Directions anymore
- The polylines are now color-coded with respect to their method of travel.
 
### Note
Scenario 4 is set up (code-wise), but we need to update the ClassRoom constant file to add classrooms from another building in order to test if it works.
To test: Checkout to branch `feature/indoor-outdoor-alain`
